# Generated by Django 5.0.2 on 2024-04-20 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Academicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letra_edificio', models.CharField(max_length=1)),
                ('numero_salon', models.IntegerField()),
                ('tipo_problema', models.CharField(max_length=100)),
                ('gravedad_problema', models.CharField(max_length=100)),
                ('descripcion_problema', models.TextField()),
                ('ubicacion_exacta', models.TextField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
