# Generated by Django 5.0.2 on 2024-04-28 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_areascomunes_baños_departamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problemas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_problematica', models.CharField(max_length=100)),
                ('estatus_problematica', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tipo_problema', models.CharField(max_length=100)),
                ('gravedad_problema', models.CharField(max_length=100)),
                ('descripcion_problema', models.TextField()),
                ('ubicacion_exacta', models.TextField()),
                ('letra_edificio', models.CharField(blank=True, max_length=1)),
                ('numero_salon', models.IntegerField(blank=True)),
                ('piso_baño', models.CharField(blank=True, max_length=100)),
                ('tipo_baño', models.CharField(blank=True, max_length=100)),
                ('TipoArea', models.CharField(blank=True, max_length=100)),
                ('UbicacionArea', models.CharField(blank=True, max_length=100)),
                ('TipoDepartamento', models.CharField(blank=True, max_length=100)),
                ('TipoEdificio', models.CharField(blank=True, max_length=100)),
                ('UbicacionDepartamento', models.CharField(blank=True, max_length=100)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemasCompletados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_adicional', models.TextField(blank=True)),
                ('fecha_completado', models.DateTimeField(auto_now_add=True)),
                ('id_administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_problema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.problemas')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemasRechazados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_adicional', models.TextField(blank=True)),
                ('fecha_rechazado', models.DateTimeField(auto_now_add=True)),
                ('reaceptado', models.BooleanField(default=False)),
                ('id_administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_problema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.problemas')),
            ],
        ),
    ]
