# Generated by Django 5.0.2 on 2024-04-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_problemas_problemascompletados_problemasrechazados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areascomunes',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='baños',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='departamento',
            name='id_usuario',
        ),
        migrations.RenameField(
            model_name='problemas',
            old_name='TipoArea',
            new_name='tipo_area',
        ),
        migrations.RenameField(
            model_name='problemas',
            old_name='TipoDepartamento',
            new_name='tipo_departamento',
        ),
        migrations.RenameField(
            model_name='problemas',
            old_name='tipo_problematica',
            new_name='tipo_edificio',
        ),
        migrations.RenameField(
            model_name='problemas',
            old_name='TipoEdificio',
            new_name='tipo_edificio_departamento',
        ),
        migrations.RenameField(
            model_name='problemas',
            old_name='UbicacionArea',
            new_name='ubicacion_area',
        ),
        migrations.RenameField(
            model_name='problemas',
            old_name='UbicacionDepartamento',
            new_name='ubicacion_departamento',
        ),
        migrations.AlterField(
            model_name='problemas',
            name='ubicacion_exacta',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Academicos',
        ),
        migrations.DeleteModel(
            name='AreasComunes',
        ),
        migrations.DeleteModel(
            name='Baños',
        ),
        migrations.DeleteModel(
            name='Departamento',
        ),
    ]
