# Generated by Django 5.0.2 on 2024-04-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_problemas_letra_edificio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemas',
            name='edificio_baño',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
