# Generated by Django 5.0.2 on 2024-04-30 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_problemas_estatus_problematica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProblemasCompletados',
            new_name='ProblemaCompletado',
        ),
        migrations.RenameModel(
            old_name='ProblemasRechazados',
            new_name='ProblemaRechazado',
        ),
        migrations.CreateModel(
            name='Problema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_edificio', models.CharField(max_length=100)),
                ('estatus_problematica', models.CharField(default='Procesando', max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tipo_problema', models.CharField(max_length=100)),
                ('gravedad_problema', models.CharField(max_length=100)),
                ('descripcion_problema', models.TextField()),
                ('ubicacion_exacta', models.TextField(blank=True, null=True)),
                ('letra_edificio', models.CharField(blank=True, max_length=1, null=True)),
                ('numero_salon', models.IntegerField(blank=True, null=True)),
                ('piso_baño', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_baño', models.CharField(blank=True, max_length=100, null=True)),
                ('edificio_baño', models.CharField(blank=True, max_length=10, null=True)),
                ('tipo_area', models.CharField(blank=True, max_length=100, null=True)),
                ('ubicacion_area', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_edificio_departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('ubicacion_departamento', models.TextField(blank=True, null=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='problemacompletado',
            name='id_problema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.problema'),
        ),
        migrations.AlterField(
            model_name='problemarechazado',
            name='id_problema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.problema'),
        ),
        migrations.DeleteModel(
            name='Problemas',
        ),
    ]
