# Generated by Django 5.0.2 on 2024-05-01 17:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_problemascompletados_problemacompletado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProblemaCompletado',
            new_name='ProblemaAceptado',
        ),
    ]
