# Generated by Django 5.0.2 on 2024-05-31 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_problemarechazado_id_administrador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemaencurso',
            name='comentario_completado',
            field=models.TextField(blank=True, null=True),
        ),
    ]
