# Generated by Django 5.0.2 on 2024-06-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='admin_u',
            field=models.CharField(default='', max_length=50),
        ),
    ]
