# Generated by Django 5.0.2 on 2024-07-10 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_notification_admin_u'),
    ]

    operations = [
        migrations.AddField(
            model_name='problema',
            name='fecha_actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
