# Generated by Django 5.0.2 on 2024-07-10 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_problema_fecha_actualizado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problemaencurso',
            old_name='id_problema',
            new_name='problema',
        ),
    ]
