# Generated by Django 5.0.2 on 2024-07-10 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_rename_id_problema_problemaencurso_problema'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problemaencurso',
            old_name='problema',
            new_name='id_problema',
        ),
    ]
